name: Pipeline Backend
on:
  push:
    branches:[ main ]
  pull_request:
    branches:[ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Install dependencies
        run:|
          python -m pip install --upgrade pip
          pip install pylint pytest flask
      -name: Pylint
        run: pylint `ls -R|grep .py$|xargs`
      -name: Pytest
        run: pytest `ls -R|grep test_*.py$|xargs`
